# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://leozhi-nian.github.io/
date_format: "ordinal"
title: 拾念
subtitle: ""
description: "拾念的个人博客"
keywords: 拾念, leozhi
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: leozhi-nian/leozhi-nian.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
  jsdelivr:
    enabled: falses

# ---------------- #
#      Author      #
# ---------------- #
author: 拾念
organization:
organization_url:
github_username: leozhi-nian
location: Henan, China
email: leozhi819@vip.qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /about/
    label: 关于

  -
    href: /links/
    label: 链接

  -
    href: /message/
    label: 留言板

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 5
paginate_path: "page:num"
lsi: false
quiet: false
excerpt_separator: "\n\n"
plugins:
  - jekyll-github-metadata
  - rouge
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji